applications/mne_x/plugins/babymeg/FormFiles/babymegsquidcontroldgl.cpp
applications/mne_x/plugins/babymeg/FormFiles/babymegsquidcontroldgl.ui
applications/mne_x/plugins/babymeg/babymeginfo.cpp

Christos, I set the default value to sampling rate if there is no lowpass filter applied. Could you know what is the default value if there is no lowpass filter applied in vectorview?

Change the lowpass to fs.

---

MNE/disp3D/3DObjects/brain/brainannotationtreeitem.cpp
MNE/disp3D/3DObjects/brain/brainhemispheretreeitem.cpp
MNE/disp3D/3DObjects/brain/brainhemispheretreeitem.h
MNE/disp3D/3DObjects/brain/brainrtsourcelocdatatreeitem.cpp
MNE/disp3D/3DObjects/brain/brainrtsourcelocdatatreeitem.h
MNE/disp3D/3DObjects/brain/brainsourcespacetreeitem.cpp
MNE/disp3D/3DObjects/brain/brainsurfacesettreeitem.cpp
MNE/disp3D/3DObjects/brain/brainsurfacetreeitem.cpp
MNE/disp3D/3DObjects/brain/braintreemodel.cpp
MNE/disp3D/3DObjects/brain/braintreemodel.h
MNE/disp3D/control/control3dwidget.cpp
MNE/disp3D/control/control3dwidget.h
MNE/disp3D/control/control3dwidget.ui
MNE/disp3D/helpers/abstracttreeitem.cpp
examples/disp3DTutorial/main.cpp

Some Disp3D improvements:
- Add description as second column in tree view.
- Create "always on top" window flag button in Control3D
- Create set function to the RT Brain Tree Item

Disp3D improvements

---

applications/mne_x/plugins/babymeg/babymeg.cpp
applications/mne_x/plugins/eegosports/FormFiles/eegosportssetupprojectwidget.cpp
applications/mne_x/plugins/eegosports/FormFiles/eegosportssetupprojectwidget.h
applications/mne_x/plugins/eegosports/FormFiles/eegosportssetupprojectwidget.ui
applications/mne_x/plugins/eegosports/eegosports.cpp
applications/mne_x/plugins/eegosports/eegosports.h
applications/mne_x/plugins/plugins.pro

Add cardinal selection support to eegosport plugin.

EEGoSport fixes

---

MNE/disp3D/3DObjects/common/metatreeitem.cpp
MNE/disp3D/3DObjects/data3Dtreedelegate.cpp
MNE/disp3D/3DObjects/digitizer/digitizertreeitem.cpp
MNE/disp3D/3DObjects/digitizer/digitizertreeitem.h
MNE/disp3D/helpers/custommesh.cpp
MNE/disp3D/helpers/custommesh.h
MNE/disp3D/helpers/types.h

Add color and visibility feature to digitizer items in Disp3D.
Fix buffer problems when compiled in debug mode.

Improve digitizer visualization

---

MNE/fiff/fiff_coord_trans.cpp
MNE/fiff/fiff_coord_trans.h

bug fix in invert_transform and apply_invers_trans added

---

MNE/disp3D/model/common/renderable3Dentity.cpp
MNE/disp3D/model/data3Dtreemodel.cpp
MNE/disp3D/model/digitizer/digitizertreeitem.cpp
MNE/disp3D/model/measurement/measurementtreeitem.cpp
MNE/rtProcessing/rthpis.cpp
applications/mne_sample_set_downloader/downloader.cpp
applications/mne_sample_set_downloader/extract.h
applications/mne_scan/libs/scDisp/helpers/realtimemultisamplearraydelegate.cpp
examples/cancelNoise/main.cpp
examples/computeInversePwlRapMusic/main.cpp
examples/computeInverseRapMusic/main.cpp
examples/connectivityTutorial/main.cpp
examples/disp3DTutorial/main.cpp
examples/evokedGradAmp/main.cpp
examples/rawClusteredInverse/main.cpp
examples/rawClusteredInversePwlRapMusic/main.cpp
examples/rawClusteredInverseRapMusic/main.cpp
examples/readEpochs/main.cpp
examples/readEvoked/main.cpp
examples/readRaw/main.cpp
examples/roiClusteredInversePwlRapMusic/main.cpp
examples/stClusteredInversePwlRapMusic/main.cpp

Fix some coverity findings, introduced during the last PR's. Please review/merge ASAP.

Fix coverity findings

---

applications/mne_dipole_fit/main.cpp

Fix gui problem in dip fit main

---

MNE/disp3D/model/workers/rtSourceLoc/rtsourcelocdataworker.cpp
MNE/disp3D/model/workers/rtSourceLoc/rtsourcelocdataworker.h
MNE/rtProcessing/rthpis.cpp
MNE/rtProcessing/rthpis.h
applications/mne_scan/libs/scDisp/helpers/realtimemultisamplearraydelegate.cpp
applications/mne_scan/libs/scDisp/helpers/realtimemultisamplearraydelegate.h
applications/mne_scan/libs/scDisp/hpiwidget.cpp
applications/mne_scan/libs/scDisp/hpiwidget.h
applications/mne_scan/plugins/babymeg/babymeg.cpp
applications/mne_scan/plugins/babymeg/babymeg.h
applications/mne_scan/plugins/fiffsimulator/fiffsimulator.cpp
applications/mne_scan/plugins/fiffsimulator/fiffsimulator.h

- Added some safe guarding
- Added VectorView support
- Improved thread safety when fitting different coils

HPI hotfixes

---

MNE/fiff/fiff_dir_node.cpp

Closes #279.
Ready for review/merge from my end.

MRG: Dont convert endianness

---

MNE/disp3D/engine/model/data3Dtreemodel.cpp
MNE/disp3D/engine/model/data3Dtreemodel.h
MNE/disp3D/engine/model/items/common/abstractmeshtreeitem.cpp
MNE/disp3D/engine/model/items/common/abstractmeshtreeitem.h
MNE/disp3D/engine/model/items/measurement/measurementtreeitem.cpp
MNE/disp3D/engine/model/items/measurement/measurementtreeitem.h
MNE/disp3D/engine/model/items/mri/mritreeitem.cpp
MNE/disp3D/engine/model/items/mri/mritreeitem.h
MNE/disp3D/engine/model/items/sourceactivity/mneestimatetreeitem.cpp
MNE/disp3D/engine/model/items/sourceactivity/mneestimatetreeitem.h
MNE/disp3D/engine/model/items/subject/subjecttreeitem.cpp
MNE/disp3D/engine/model/items/subject/subjecttreeitem.h
applications/mne_scan/libs/scDisp/hpiwidget.cpp
examples/ex_disp_3D/main.cpp

Prepare disp3D for real time field pattern visualization

RT field pattern visualization

---

README.md
applications/mne_rt_server/connectors/Neuromag/neuromag.cpp
applications/mne_scan/plugins/neuromag/neuromag.cpp
applications/mne_scan/plugins/neuromag/neuromagproducer.cpp
appveyor.yml
mne-cpp.pri
tools/travis/coverity/before_install.sh
tools/travis/coverity/install.sh
tools/travis/linux_release/before_install.sh
tools/travis/linux_release/install.sh
tools/travis/linux_tests/before_install.sh
tools/travis/linux_tests/install.sh

- Fix resource problem in Neuromag
- Change default buffer size in Neuromag back to 600
- Add some extra fail safe mechanisms to the Neuromag plugin producer
- Bump up Qt version to 5.10

MNE Scan Neuromag plugin fixes

---

applications/mne_analyze/mne_analyze/mne_analyze.pro
applications/mne_browse/mne_browse.pro
applications/mne_dipole_fit/mne_dipole_fit.pro
applications/mne_forward_solution/mne_forward_solution.pro
applications/mne_launch/mne_launch.pro
applications/mne_launch/mnelaunchcontrol.cpp
applications/mne_matching_pursuit/mne_matching_pursuit.pro
applications/mne_rt_server/mne_rt_server/mne_rt_server.pro
applications/mne_sample_set_downloader/mne_sample_set_downloader.pro
applications/mne_scan/libs/scDisp/helpers/realtimemultisamplearraymodel.cpp
applications/mne_scan/libs/scDisp/hpiwidget.cpp
applications/mne_scan/libs/scDisp/realtimemultisamplearraywidget.cpp
applications/mne_scan/mne_scan/mne_scan.pro
applications/mne_scan/plugins/fiffsimulator/fiffsimulator.cpp
applications/mne_show_fiff/mne_show_fiff.pro
examples/ex_deep/main.cpp
examples/ex_deep_eval/main.cpp
examples/ex_disp_3D/main.cpp
libraries/disp/selectionmanagerwindow.cpp
libraries/fwd/computeFwd/compute_fwd.cpp
libraries/fwd/fwd_bem_model.cpp
libraries/inverse/dipoleFit/dipole_fit_data.cpp

- Fix MNE Launch for MacOS
- Fix resource loading for MacOS
- Add QMAKE_CLEAN for MacOS applications
- Fix QML deploy for Windows

Deployment hotfixes

---

applications/mne_scan/libs/scDisp/realtimeconnectivityestimatewidget.cpp
applications/mne_scan/plugins/averaging/averaging.cpp
applications/mne_scan/plugins/mne/mne.cpp
applications/mne_scan/plugins/neuronalconnectivity/neuronalconnectivity.cpp
examples/ex_connectivity/connectivitysettingsmanager.h
examples/ex_connectivity_comparison/main.cpp
libraries/connectivity/network/network.cpp
libraries/connectivity/network/network.h
libraries/disp/viewers/connectivitysettingsview.cpp
libraries/disp/viewers/connectivitysettingsview.h
libraries/disp3D/engine/model/items/measurement/measurementtreeitem.cpp
libraries/disp3D/viewers/networkview.cpp
libraries/rtprocessing/rtconnectivity.cpp
mne-cpp.pri

- Fix mutex problem in mne plugin in MNE Scan
- Rename set and get frequency range function ins Network class
- Fix saving loading-saving setting in ConnectivitySettingsView

MNE Scan Hotfix

---

.gitignore
applications/mne_analyze/extensions/music/music.cpp
applications/mne_scan/libs/scDisp/realtimesourceestimatewidget.cpp
applications/mne_scan/libs/scDisp/realtimesourceestimatewidget.h
examples/ex_clustered_inverse_mne/main.cpp
examples/ex_clustered_inverse_mne_raw/main.cpp
examples/ex_clustered_inverse_pwl_rap_music_raw/main.cpp
examples/ex_clustered_inverse_rap_music_raw/main.cpp
examples/ex_connectivity/main.cpp
examples/ex_connectivity_comparison/main.cpp
examples/ex_disp_3D/main.cpp
examples/ex_inverse_mne_raw/main.cpp
examples/ex_inverse_pwl_rap_music/main.cpp
examples/ex_inverse_rap_music/main.cpp
examples/ex_roi_clustered_inverse_pwl_rap_music/main.cpp
examples/ex_st_clustered_inverse_pwl_rap_music/main.cpp
libraries/disp3D/disp3D.pro
libraries/disp3D/engine/model/data3Dtreemodel.cpp
libraries/disp3D/engine/model/data3Dtreemodel.h
libraries/disp3D/engine/model/items/common/types.h
libraries/disp3D/engine/model/items/hemisphere/hemispheretreeitem.cpp
libraries/disp3D/engine/model/items/measurement/measurementtreeitem.cpp
libraries/disp3D/engine/model/items/measurement/measurementtreeitem.h
libraries/disp3D/engine/model/items/sourcedata/mnedatatreeitem.cpp
libraries/disp3D/engine/model/items/sourcedata/mnedatatreeitem.h
libraries/disp3D/viewers/sourceestimateview.cpp
libraries/disp3D/viewers/sourceestimateview.h

Hi. 
Not used to qt/cpp here.  
I've a branch here to try to rename the class throughout the code. By now: 
- Renamed the class file and its header.
- Changed all its references throughout the code. 
- Built for release, debug and profiling configs and all 3 were fine. (lots of warnings but OK).
Although I found the 
```
"Error: dependent '..\ some-file' does not exist." 
```
To solve it I had to "Run qmake" before clean and build.
I would feel much better if someone could try the code itself. I would propose either: 
- someone to fork it from me, execute and try a few examples, fix and PR if something is wrong.
- (probably better) to (i) create a branch in mne-tools/mne-cpp from master and accept the PR there. And (ii) someone to fetch that branch and do the testing there, etc... until …

mneESTIMATEtreeitem -> mneDATAtreeitem

---

tools/travis/linux_release/after_success.sh

Corresponds to issue #378. Also increase timeout.

Use quotations when uploading via curl

---

tools/travis/documentation/after_success.sh
tools/travis/documentation/install.sh

Use git lfs to upload large files.

Use git lfs when deploying doxygen

---

libraries/fiff/fiff_coord_trans.h
libraries/fiff/fiff_named_matrix.h
libraries/mne/mne_cluster_info.h
libraries/mne/mne_forwardsolution.h
libraries/mne/mne_hemisphere.h
libraries/mne/mne_sourcespace.h
testframes/test_mne_forward_solution/test_mne_forward_solution.cpp

Add equal operator to MNEHemisphere and MNESourceSpace and use them in test_mne_forward_solution

Add equal operator to MNEHemisphere and MNESourceSpace

---

codecov.yml

Exclude include folder recursively

Codecov yml

---

.travis.yml
codecov.yml

update mantainers emails in travis notif script
Also remove one space from codecov.yml

add @juangpc email to travis & update Lorenz's

---

applications/mne_analyze/extensions/surfer/Views/view3danalyze.cpp
applications/mne_browse/Models/rawmodel.cpp
applications/mne_matching_pursuit/editorwindow.cpp
applications/mne_matching_pursuit/enhancededitorwindow.cpp
applications/mne_matching_pursuit/formulaeditor.cpp
applications/mne_matching_pursuit/mainwindow.cpp
applications/mne_matching_pursuit/settingwindow.cpp
applications/mne_rt_server/plugins/neuromag/shmemsocket.cpp
applications/mne_scan/libs/scDisp/realtimeevokedsetwidget.cpp
applications/mne_scan/plugins/epidetect/calcmetric.cpp
applications/mne_scan/plugins/epidetect/epidetect.cpp
applications/mne_scan/plugins/mne/mne.cpp
applications/mne_scan/plugins/natus/natusproducer.cpp
applications/mne_scan/plugins/neuromag/neuromag.cpp
applications/mne_scan/plugins/neuronalconnectivity/neuronalconnectivity.cpp
applications/mne_scan/plugins/noisereduction/noisereduction.cpp
applications/mne_scan/plugins/ssvepbci/FormFiles/ssvepbciconfigurationwidget.cpp

fixes for coverity issues from the nov 27 scan

Coverity Issues

---

applications/mne_matching_pursuit/mainwindow.cpp
applications/mne_matching_pursuit/mainwindow.h
applications/mne_rt_server/plugins/neuromag/shmemsocket.cpp
applications/mne_scan/libs/scShared/Interfaces/IIO.h
applications/mne_scan/mne_scan/pluginscene.cpp
applications/mne_scan/plugins/neuromag/neuromag.cpp
applications/mne_scan/plugins/neuronalconnectivity/neuronalconnectivity.cpp
applications/mne_scan/plugins/noisereduction/noisereduction.cpp
applications/mne_scan/plugins/reference/eegref.cpp
applications/mne_scan/plugins/ssvepbci/screenkeyboard.cpp
examples/ex_clustered_inverse_mne_raw/main.cpp
examples/ex_clustered_inverse_pwl_rap_music_raw/main.cpp
examples/ex_clustered_inverse_rap_music_raw/main.cpp
examples/ex_connectivity/main.cpp
examples/ex_connectivity_comparison/main.cpp
examples/ex_connectivity_performance/main.cpp
examples/ex_inverse_mne_raw/main.cpp
libraries/disp/viewers/rtfiffrawview.cpp
libraries/mne/mne_forwardsolution.cpp

- initialized uninitialized variables in constructors
- added else/defaults to prevent unknown behavior
- removed throw() that was not caught in any of the examples
- changed rand() to qt equivalent
- other minor changes

Coverity changes

---

applications/mne_browse/Utils/filterplotscene.cpp
examples/ex_connectivity_performance/main.cpp
examples/ex_fiff_io/main.cpp
libraries/disp/viewers/butterflyview.cpp
libraries/disp3D/engine/model/data3Dtreemodel.cpp
libraries/disp3D/engine/model/items/digitizer/digitizersettreeitem.cpp
libraries/disp3D/engine/model/items/sourcedata/ecddatatreeitem.cpp
libraries/disp3D/engine/model/workers/rtSourceLoc/rtsourcedataworker.cpp
libraries/disp3D/helpers/geometryinfo/geometryinfo.cpp
libraries/mne/mne_cluster_info.cpp

- variable initialization in constructors
- casting operands
- checks and warning messages for variables obtaining data

Coverity part3

---

testframes/test_fiff_digitizer/test_fiff_digitizer.cpp
testframes/test_fiff_mne_types_io/test_fiff_mne_types_io.cpp
testframes/test_fiff_rwr/test_fiff_rwr.cpp
testframes/test_mne_forward_solution/test_mne_forward_solution.cpp

Changed from old test file (sample_audvis_raw_short) to new test file (sample_audvis_trunc_raw)

changed file addresses to new test file

---

.github/workflows/devbuilds.yml
doc/mne-cpp_doxyfile

Forgot to remove if statement from non matrix based devbuild.yml workflow -_-

Fix jom install in devbuilds.yml

---

libraries/disp3D/engine/model/data3Dtreemodel.cpp
libraries/disp3D/engine/model/data3Dtreemodel.h
libraries/disp3D/engine/model/items/common/types.h

Add QVector<int> to qRegisterMatatypes

Disp3D fix

---

.github/workflows/pullrequest.yml
applications/mne_browse/Models/rawmodel.cpp
applications/mne_browse/Models/rawmodel.h
applications/mne_browse/Windows/mainwindow.cpp
applications/mne_browse/mne_browse.pro
libraries/disp/viewers/butterflyview.h
libraries/fiff/fiff.pro
libraries/fiff/fiff_id.cpp
libraries/fiff/fiff_tag.h
libraries/fwd/fwd.pro
libraries/inverse/inverse.pro
mne-cpp.pri

- Fixed some compilation errors encountered when building with wasm flag.
- Libraries build fine now. Disp3D is commented out because of lack of QtWasm support for Qt3D.

Fix wasm incompabilities

---

doc/gh-pages/index.md
doc/gh-pages/pages/contribute/conv_style.md
doc/gh-pages/pages/development/build_run_depl_pack.md
doc/gh-pages/pages/development/eeg_amp_scan.md
doc/gh-pages/pages/development/neuromag.md
doc/gh-pages/pages/development/qtwasmtutorial.md
doc/gh-pages/pages/development/scan_plugin.md
doc/gh-pages/pages/install/buildguide.md
doc/gh-pages/pages/learn/source_loc_example.md
doc/gh-pages/pages/learn/ssvep_bci_example.md

Some improvements to the docu pages.

Improve docu

---

doc/gh-pages/pages/development/ci.md
doc/gh-pages/pages/development/scan_plugin.md

- Rename Build/Run & Deployment & Packaging/Distribution page to CI Pipeline
- Fix pdf link

Improve docu pages

---

.github/workflows/docutest.yml
doc/gh-pages/pages/contribute/conv_style.md
doc/gh-pages/pages/contribute/docuimprovements.md
doc/gh-pages/pages/development/development.md

- Add a guide to explain how to change and check MNE-CPP's static website

Add documentation contribution guide

---

applications/mne_scan/plugins/noisereduction/noisereduction.cpp

Fix creation of picks vector in noise reduction plugin

---

.github/workflows/coverity.yml
.github/workflows/devbuilds.yml
.github/workflows/pullrequest.yml

Change Install Qt action to ouuan/install-qt-action@v2.3.1 Github Action temporarily. See jurplel/install-qt-action#27.

MAINT: Change to ouuan/install-qt-action@v2.3.1 Github Action 

---

.github/workflows/coverity.yml
.github/workflows/devbuilds.yml
.github/workflows/pullrequest.yml

This PR fixes the deadlock problem described here: https://github.com/miurahr/aqtinstall/issues/91. Also, bumps Qt 5.14.0 to 5.14.1.

[MAINT] Update python version in GithubAction workflows

---

doc/gh-pages/pages/started/started.md
libraries/fiff/fiff_file.h

As described in mne-tools/fiff-constants#26

[ENH] Add ambidextrous to handedness option

---

libraries/disp3D/engine/view/view3D.cpp
libraries/disp3D/helpers/geometryinfo/geometryinfo.cpp
libraries/disp3D/helpers/geometryinfo/geometryinfo.h

- Fix issue where the surface constrained distance calculation and sensor projection failed when setting up their multithreaded compuation.
- Fix problem where the lights in the 3D scene did not have any effect on Linux.
Fixes #466

[FIX] Fix activity interpolation and lighting in Disp3D

---

libraries/disp3D/engine/model/3dhelpers/renderable3Dentity.cpp
libraries/disp3D/engine/model/3dhelpers/renderable3Dentity.h

Fix add/set functions in Renderable3DEntity

[FIX] Fix transforms in Disp3D

---

.github/workflows/coverity.yml
.github/workflows/devbuilds.yml
.github/workflows/docutest.yml
.github/workflows/pullrequest.yml
applications/mne_scan/plugins/brainflowboard/FormFiles/brainflowsetupwidget.cpp
doc/gh-pages/overview.md
doc/gh-pages/pages/development/brainflow.md

Try to build BrainFlow plugin in CI

[ENH] try to build brainflow plugin in CI

---

.github/workflows/devbuilds.yml
.github/workflows/pullrequest.yml

[FIX] Fix path for brainflow libs

---

.github/workflows/devbuilds.yml
.github/workflows/pullrequest.yml
applications/mne_scan/plugins/plugins.pro
mne-cpp.pri

Introduce withBrainFlow CONFIG flag. This eases setting up MNE-CPP with Brainflow support during the CI.

[FIX,MAINT] Add brainflow module config flag

---

.github/workflows/devbuilds.yml
applications/mne_scan/plugins/brainflowboard/brainflowboard.pro

- Fix path problem in Linux workflow in devbuilds.yml
- Add target name in brainflowboard.pro

[FIX,MAINT] Changes to devbuilds.yml and BrainFlowBoard plugin

---

.github/workflows/devbuilds.yml
.github/workflows/pullrequest.yml
.gitmodules
applications/mne_scan/plugins/lsladapter/FormFiles/lsladaptersetup.cpp
applications/mne_scan/plugins/lsladapter/lsladapter.h
applications/mne_scan/plugins/lsladapter/lsladapter.pro
applications/mne_scan/plugins/lsladapter/lsladapter_global.h
applications/mne_scan/plugins/plugins.pro
doc/gh-pages/pages/development/brainflow.md
doc/gh-pages/pages/development/lsl.md
doc/gh-pages/pages/development/scan_plugin.md
mne-cpp.pri

[DOC,ENH] Add LSL docu and LSL plugin to pre-built binaries

---

examples/ex_hpiFit/main.cpp
libraries/communication/rtClient/rtdataclient.cpp
libraries/fiff/fiff_explain.h
libraries/fiff/fiff_file.h
libraries/fiff/fiff_info.cpp
libraries/fiff/fiff_info.h
libraries/fiff/fiff_stream.cpp
testframes/test_hpiFit/test_hpiFit.pro

This PR adds following information to FiffInfo:
- linefreq
- proj_id
- xplotter_layout
- experimenter   
- description     
- utc_offset      
- gantry_angle
It closes #543

[ENH] Add information to FiffInfo

---

doc/gh-pages/pages/development/qtwasmtutorial.md

Update WASM tutorial with Qt 5.15 info and fix git clone command mistake.

[DOCU] Update WASM tutorial

---

applications/mne_scan/plugins/brainflowboard/FormFiles/brainflowsetupwidget.cpp

new release of brainflow supports [unicorn device](https://www.unicorn-bi.com/)(for now only on linux)

[ENH] Update brainflow version to add unicorn

---

.github/workflows/devbuilds.yml

Fix a bug when packaging for the linux static build.

[MAINT] Fix packaging for linux static build

---

.github/workflows/devbuilds.yml
.github/workflows/wasmtest.yml
doc/gh-pages/pages/development/wasmtesting.md

Some fixes to the wasm Githu Actions workflows.

[MAINT] Wasm CI workflow fixes

---

applications/mne_forward_solution/main.cpp
examples/ex_compute_forward/ex_compute_forward.pro
examples/ex_compute_forward/main.cpp
examples/examples.pro
libraries/fiff/c/fiff_coord_trans_old.cpp
libraries/fiff/c/fiff_coord_trans_old.h
libraries/fiff/fiff_coord_trans.cpp
libraries/fiff/fiff_coord_trans.h
libraries/fwd/computeFwd/compute_fwd.cpp
libraries/fwd/computeFwd/compute_fwd.h
libraries/fwd/computeFwd/compute_fwd_settings.cpp
libraries/fwd/computeFwd/compute_fwd_settings.h
libraries/fwd/fwd_bem_model.cpp
libraries/fwd/fwd_bem_model.h
libraries/mne/mne_forwardsolution.h
testframes/test_mne_forward_solution/test_mne_forward_solution.cpp

This PR aims to make head position updates to the forward solution possible. Therefore I had to introduce a couple of changes.
1. Split computeForward into:
- initFwd() that contains initialization, loading and preparation of source space, coil set and bem model
- calculateFwd() - actual calculation of the MEG and EEG forward solution
- storeFwd() - write solution to file
2. Make the most important variables a member for ComputeFwd()
- ToDo: once refactored MNEForwardSolution should be the main output that stores the solution for further use
3. Add function updateHeadPos() that takes a meg->head transformation and recalculates the meg forward solution for updated coil set
- ToDo: once refactored it might be possible to recalculate a bit less
4. Update test_mne_forward_solution
5. Add …

[ENH,MAINT] Update Fwd. Solution with new Head Position 

---

applications/mne_analyze/extensions/annotationmanager/annotationdelegate.cpp
applications/mne_analyze/extensions/annotationmanager/annotationdelegate.h
applications/mne_analyze/extensions/annotationmanager/annotationview.cpp
applications/mne_analyze/extensions/annotationmanager/annotationview.h
applications/mne_analyze/extensions/annotationmanager/annotationview.ui
applications/mne_analyze/extensions/rawdataviewer/fiffrawviewdelegate.cpp
applications/mne_analyze/libs/anShared/Model/annotationmodel.cpp
applications/mne_analyze/libs/anShared/Model/annotationmodel.h

- Real time display when updating annotation values (time and sample values)
- Mutiple selection (and deletion)
- Organize GUI

[ENH, MAINT] MNE Analyze features and release cleanup

---

doc/gh-pages/index.md
doc/gh-pages/overview.md
doc/gh-pages/pages/install/binaries.md
doc/gh-pages/pages/install/install.md
doc/gh-pages/pages/learn/mneanalyze.md
doc/gh-pages/pages/started/started.md

- Overview page layout content, attribution to Matti and other MNE projects
- Release page links static and dynamic build, new section for wasm
- Getting started page redone
- fixed some typos
see preview here: https://gabrielbmotta.github.io/mne-cpp/

[DOC, MAINT] gh-pages layout and content

---

.github/workflows/release.yml
doc/doxygen/mne-cpp_doxyfile
doc/gh-pages/index.md
doc/gh-pages/overview.md
doc/gh-pages/pages/development/ci.md
doc/gh-pages/pages/install/binaries.md
doc/gh-pages/pages/install/changelog.md
mne-cpp.pri

- Increment version number to 0.1.0
- Rename "Overview" section to "About"
- Add changelog.md and link to it in the release binary table

[DOCU,MAINT] Increment version number and documentation

---

.github/workflows/release.yml

This PR changes `mne_analyze_extensions` to `mne_analyze_plugins` folder in release.yml.

[MAINT,FIX] Fix problems in release CI workflow

---

applications/mne_analyze/mne_analyze/mne_analyze.pro

Fix copying of mne analyze plugins on macos. #593

[Fix] Fix mne analyze plugin deployment on macos

---

applications/mne_analyze/mne_analyze/mainwindow.cpp
applications/mne_analyze/plugins/rawdataviewer/rawdataviewer.cpp
libraries/fiff/fiff_raw_data.cpp

- Suppressed [done] messages. Closes #604  
- Added plugins to View menu. Closes #608

[FIX] MNE Analyze Issues - reopen plugins and command line cleanup

---

applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp
applications/mne_analyze/plugins/rawdataviewer/fiffrawview.h

- Added sample/time labels tracking position in file. closes #603 
Preview:

[ENH] MNE Analyze - Scroll Labels

---

.github/workflows/docutest.yml
doc/gh-pages/pages/contribute/docuimprovements.md
doc/gh-pages/pages/development/deployment.md
doc/gh-pages/pages/learn/mneanonymize.md

Hi,
I'm surprised how bad git tracks text changes. The changes are really small, please mostly disregard whole paragraph changes.

[DOC] Minor edits deployment and mne_anonymize

---

applications/mne_analyze/mne_analyze/mainwindow.cpp
applications/mne_scan/mne_scan/mainwindow.cpp

Made application load dock icons for mne analyze and mne scan

[MAINT] MNE Analyze / Scan - linux dock icons

---

applications/mne_analyze/libs/anShared/anShared.pro
applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp
applications/mne_scan/libs/scDisp/scDisp.pro
applications/mne_scan/libs/scMeas/scMeas.pro
applications/mne_scan/libs/scShared/scShared.pro
applications/mne_scan/plugins/ftbuffer/ftconnector.cpp
doc/gh-pages/pages/development/deployment.md
doc/gh-pages/pages/install/changelog.md

- Fix deployment of MNE analyze and MNE Scan libraries on Windows
- Fix some typos in the documentation

[DOC,MAINT] Deployment and docu fixes

---

applications/mne_analyze/libs/anShared/Management/analyzedatamodel.cpp
applications/mne_analyze/libs/anShared/Management/analyzedatamodel.h
applications/mne_analyze/libs/anShared/Model/annotationmodel.cpp
applications/mne_analyze/mne_analyze/mainwindow.cpp
applications/mne_analyze/plugins/annotationmanager/annotationmanager.cpp
applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.cpp
applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.ui
applications/mne_analyze/plugins/datamanager/FormFiles/datamanagerview.cpp
applications/mne_analyze/plugins/datamanager/FormFiles/datamanagerview.h
applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp
applications/mne_analyze/plugins/rawdataviewer/fiffrawview.h
applications/mne_analyze/plugins/rawdataviewer/rawdataviewer.cpp
libraries/disp/viewers/fiffrawviewsettings.cpp
libraries/disp/viewers/fiffrawviewsettings.h
libraries/disp/viewers/formfiles/scalingview.ui
libraries/disp/viewers/scalingview.cpp

- Log Window now has location preserved between sessions
- Files once again get selected and displayed automatically when first loaded
- Disconnect everything from old model before loading new one. Exclusive connections throughout.
- Signal Viewer and Annotation settings scale depending on available size. Visual cleanup.

[MAINT, FIX] MNE Analyze: bugfixes, GUI cleanup

---

applications/mne_scan/plugins/brainflowboard/brainflowboard.cpp

[MAINT,ENH] Update brainflow

---

applications/mne_analyze/plugins/datamanager/FormFiles/datamanagercontrolview.cpp
applications/mne_analyze/plugins/datamanager/FormFiles/datamanagercontrolview.h
applications/mne_analyze/plugins/datamanager/datamanager.cpp
applications/mne_analyze/plugins/datamanager/datamanager.pro

Refactored DataManagerView to DataManagerControlView, added a break case to switch statement in datamanager.cpp

[ENH] Rename DataManagerView class

---

doc/gh-pages/pages/install/binaries.md
doc/gh-pages/pages/install/changelog.md
libraries/disp/viewers/filterdesignview.cpp
libraries/disp/viewers/helpers/rtfiffrawviewmodel.cpp
libraries/rtprocessing/filter.cpp
libraries/rtprocessing/helpers/filterio.cpp
libraries/rtprocessing/helpers/filterkernel.cpp
libraries/rtprocessing/helpers/filterkernel.h

Remove some deep copies when filtering in order to speed up filtering

[ENH] Remove unnecesarry data copies when filtering

---

applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp
applications/mne_analyze/plugins/rawdataviewer/fiffrawview.h

- FiffRawView now inherits from Abstract view
- Window size and number of channels preserved while resizing window.

[MAINT] MNE Analyze - Viewer Resizing

---

doc/gh-pages/pages/learn/sample_data.md

Add guide on how to install the MNE Sample Data Set

[DOCU] Add guide on how to install the MNE Sample Data Set

---

doc/gh-pages/pages/development/analyze_datamodel.md
doc/gh-pages/pages/development/analyze_event.md

- Added page on the event system
- Added page on creating data models

[DOC] MNE Analyze - documenting event system and data model creation

---

.github/workflows/pullrequest.yml
.github/workflows/release.yml

- Fix CI problems when releasing dev/stable builds. 
- Add checks for packaging steps.

[MAINT] Fix CI problems when releasing dev/stable builds. Add checks for packaging steps.

---

libraries/mne/mne_project_to_surface.cpp
testframes/test_mne_project_to_surface/test_mne_project_to_surface.cpp
testframes/test_mne_project_to_surface/test_mne_project_to_surface.pro
testframes/testframes.pro

This PR implements a test for MNEProjectToSurface.
Approach:
- Take MNEBemSurface and multiply triangle centers with 1.5 (arbitrary value)
- Project these values to the original surface 
- compare the result to referene values merged computed with the same function and merged with https://github.com/mne-tools/mne-cpp-test-data/pull/9

[WIP,ENH] Test for MNEProjectToSurface

---

libraries/disp/viewers/formfiles/channelselectionview.ui

- Remove max size on widget items, change size preference.

[FIX] Adjust scaling on Channel Selection

---

.github/workflows/pullrequest.yml
.github/workflows/release.yml
applications/mne_scan/plugins/brainflowboard/FormFiles/brainflowsetupwidget.cpp

[MAINT,ENH] Bump brainflow version

---

applications/mne_analyze/libs/anShared/Utils/metatypes.h
applications/mne_analyze/libs/anShared/Utils/types.h
applications/mne_analyze/plugins/controlmanager/controlmanager.cpp
applications/mne_analyze/plugins/controlmanager/controlmanager.h
applications/mne_analyze/plugins/controlmanager/controlmanager.pro
applications/mne_analyze/plugins/view3d/view3d.cpp
applications/mne_analyze/plugins/view3d/view3d.h
libraries/disp/viewers/helpers/selectionsceneitem.h
libraries/disp3D/engine/model/items/common/types.h

- Moved View3D controls to settings view.
- New event and struct for sending settings.

[MAINT] Move View 3D controls to settings app

---

applications/mne_analyze/plugins/averaging/averaging.cpp
libraries/disp/viewers/formfiles/averagingsettingsview.ui

- Fix GUI spacing in averaging plugin

[MAINT] MNE Analyze: Fix spacing in averaging plugin

---

.github/workflows/pullrequest.yml
.github/workflows/release.yml

* Fix wrong Visual Studio version in the CI workflow

[MAINT] Fix windows CI workflow

---

doc/gh-pages/pages/development/scan_eegosports.md

[DOC] Update eegosports docu

---

doc/gh-pages/contact.md

Update Lorenz's and add Juan's email address.

[DOC] Update email addresses

---

doc/gh-pages/feature_catalogue.md

Started to accumulate all features of the MNE-CPP applications and libraries in a single docu/website page. Progress can be checked here: http://lorenze.github.io/mne-cpp/feature_catalogue.html

[WIP][DOC] Feature catalogue

---

applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.cpp
applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.h
applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp
applications/mne_analyze/plugins/rawdataviewer/fiffrawview.h
libraries/rtprocessing/helpers/filterkernel.cpp
libraries/rtprocessing/helpers/filterkernel.h

- Display file info beneath signal viewer

[ENH] MNE Analyze - display info about file in signal viewer

---

applications/mne_scan/plugins/ftbuffer/FormFiles/ftbuffersetup.ui
applications/mne_scan/plugins/ftbuffer/FormFiles/ftbuffersetupwidget.cpp
applications/mne_scan/plugins/ftbuffer/FormFiles/ftbuffersetupwidget.h
applications/mne_scan/plugins/noisereduction/noisereduction.cpp

- update signal slot syntax and class names in ftbuffer
- change plugin name for Filter plugin (formerly noise)

[MAINT,FIX] MNE Scan - plugin maintenance

---

.github/workflows/coverity.yml

Fix of pull request https://github.com/mne-tools/mne-cpp/pull/783.

Fixed submission of coverity (e-mail addresses)

---

README.md

As the title indicates, this PR updates some old links in the project readme.

[Maint] update links to project website in project readme

---

README.md

Sorry, this was introduced by a classic 'quick fix' before lunchbreak #786.

[Fix] Add missing parentheses

---

applications/mne_scan/plugins/writetofile/FormFiles/writetofilesetupwidget.cpp
applications/mne_scan/plugins/writetofile/writetofile.cpp
applications/mne_scan/plugins/writetofile/writetofile.h

- Fix startup widget checkbox in WriteToFile.
- Add missing documentation and remove unused mutex.

[MAINT, DOC] MNE Scan - small WriteToFile fixes

---

applications/mne_scan/plugins/babymeg/FormFiles/babymegsetup.ui
applications/mne_scan/plugins/babymeg/FormFiles/babymegsetupwidget.cpp
applications/mne_scan/plugins/babymeg/FormFiles/babymegsetupwidget.h
applications/mne_scan/plugins/babymeg/babymeg.cpp

- Remove blocking check for initialization of FiffInfo before it can be initialized.
- Remove 'Connect' tab and associated functions.

[MAINT] BabyMEG plugin tweaks

---

applications/mne_scan/libs/scShared/Management/pluginmanager.cpp

[FIX, MNE_Scan] don't dereference null pointer

---

.github/workflows/release.yml

- Build for Mac without app bundles

MAINT: Release script app bundles

---

.github/workflows/release.yml

This reverts commit d9793add0d61f829865234bb99c4305d83856b32.

Revert "MAINT: no app bundles"

---

.github/workflows/buildqtbinaries.yml
.github/workflows/coverity.yml
.github/workflows/pullrequest.yml
.github/workflows/release.yml
.github/workflows/testci.yml

- Update runners from 16.04 to 18.04. Unsure if minQt workflows running Qt 5.10 will like this.
- Might be a good time to discuss minimum requirements for compilers and OSs.

WIP [MAINT] Update CI linux runner version

---

applications/mne_analyze/plugins/coregistration/coregistration.cpp
applications/mne_scan/plugins/rtfwd/rtfwd.cpp
libraries/disp/viewers/rtfiffrawview.cpp
libraries/fiff/fiff_info.cpp
libraries/fiff/fiff_info.h
libraries/fiff/fiff_info_base.h
libraries/fiff/fiff_named_matrix.cpp
libraries/fiff/fiff_named_matrix.h
libraries/fwd/computeFwd/compute_fwd.cpp
libraries/fwd/fwd_coil_set.h
libraries/inverse/c/mne_meas_data.cpp
libraries/inverse/dipoleFit/dipole_fit_data.cpp
libraries/mne/c/mne_raw_info.cpp

[FIX] Fix leaks in mne-c related libraries and few other classes

---

LICENSE
README.md

Correct the license that the authors are the holders of the license not the non existing organization MNE-CPP

MAINT: update license

---

libraries/fiff/fiff_dig_point.h

[FIX] Fix storagesize fcn

---

libraries/inverse/dipoleFit/ecd_set.cpp

(Coverity 159841 Logically dead code)

FIX: Remove goto and return false directly.

---

applications/mne_scan/libs/scShared/Management/pluginscenemanager.cpp
applications/mne_scan/libs/scShared/Management/pluginscenemanager.h
applications/mne_scan/plugins/ftbuffer/ftbuffer.cpp
applications/mne_scan/plugins/ftbuffer/ftconnector.cpp

- Add outs for loops where fetching data could get stuck.
- Change order of function calls when ending measurements.

[MAINT] Stability improvements to stopping measurements in FtBuffer and MNE Scan

---

applications/mne_anonymize/mne_anonymize.pro

[FIX] Add correct check for clang.... again

---

applications/mne_scan/plugins/ftbuffer/ftconnector.cpp

- Remove check that causes function to return early, causing a crash.

[MAINT]Remove check code that causes error.

---

examples/ex_fiff_sniffer/main.cpp

FIX: Coverity 238396 Unchecked return value

---

codecov.yml

Apparently (https://docs.codecov.com/docs/commit-status) it has to be held in the correct cascaded structure.

update codecov yml file

---

libraries/disp/viewers/formfiles/scalecontrol.ui
libraries/disp/viewers/helpers/scalecontrol.cpp
libraries/disp/viewers/helpers/scalecontrol.h

- Add menu button to side of slider to edit min/max values.

[ENH] Add ability to change min and max scale values at run time.

---

.github/workflows/release.yml
.github/workflows/wasmtest.yml
tools/deployment/wasm.sh

- Added was script for downloading and building dependencies and the project.
- Used script in GitHub Actions.
- Changed GitHub Actions to use newer versions of emsdk (3.1.20) and qt (5.15.5)

[ENH,MAINT] WASM script

---

.github/workflows/release.yml

- Remove unnecessary directory change due to working directory set for job.

[FIX] WASM gh action fix

---

applications/mne_analyze/plugins/sampleplugin/sampleplugin.cpp
applications/mne_analyze/plugins/sampleplugin/sampleplugin.h
applications/mne_analyze/plugins/sampleplugin/sampleplugin.pro
applications/mne_analyze/plugins/sampleplugin/sampleplugin_global.cpp
applications/mne_scan/plugins/dummytoolbox/dummytoolbox.cpp
applications/mne_scan/plugins/dummytoolbox/dummytoolbox.h
applications/mne_scan/plugins/dummytoolbox/dummytoolbox.pro
applications/mne_scan/plugins/dummytoolbox/dummytoolbox_global.cpp
applications/mne_scan/plugins/plugins.pro

I've added buildDate to mne scan, I'll add to mne analyze and let you know when its ready for review.

[MAINT] Add buildDate and hash goodies to dummytoolbox

---

.github/workflows/pullrequest.yml
.github/workflows/release.yml
.gitignore
src/CMakeLists.txt
tools/building/build_project.bat
tools/building/download_codecov.sh
tools/testing/test_all.bat

Update code coverage script with correct paths and build with correct linker and compiler flags.

Fix code coverage

---

.gitignore

[ENH] Add IDE session file to gitignore

---

.github/workflows/coverity.yml

Change build command in an attempt to fix coverity scan. Also update qt version in the meantime.

[MAINT, FIX] Update Coverity Scan

---

src/applications/mne_anonymize/settingscontrollercl.cpp

Not sure how I forgot about this. But it shouldn't be there uncommented.

[FIX] Comment debug printout of command arguments

---

tools/deploy.bat

This allows to distribute the out/Release folder upon successful build.
I would need someone else to validate the script in their workstation/ user configuration.

[ENH] Add martinos flag in linux deploy script

---

tools/download_data.bat

Data downloader script has a problem in linux. Think now solved. 
Please verify.

[FIX] Fix curl command data downloader

---

.github/workflows/release.yml

Change call to wasm script path to correct path.

Fix wasm script path in actions script
