MNE/generics/circularmatrixbuffer.h
I noticed this extremely helpful error was commented out. Without this print statement, `push` fails silently, and it can take a long time for a developer new to the mne-cpp ecosystem to dig down far enough to find the problem.
Is there a reason it was commented out in the first place?
=> Uncommented important error message

.gitignore
Compiling in Fedora produces `.debug` and `.so.debug` files in the /bin directory. This commit adds such files to .gitignore so that they are not tracked.
=> Added Fedora library extensions to gitignore

applications/mne_scan/plugins/epidetect/epidetect.cpp
There is an `if` statement in `epidetect.cpp` on line 347 that appears to be missing an `=`. I believe it is meant to be checking the value of `counter`, but instead it is overwriting it.
=> Changed = to == inside if statement

.gitignore
The .gitignore file was missing entries for some of the newer test binaries. This pull requests adds them.
=> Update .gitignore to ignore new test binaries

applications/mne_analyze/mne_analyze/mne_analyze.pro, examples/ex_histogram/ex_histogram.pro
MNE Analyze and the histogram example were missing linker directives for the GeometryInfo and Interpolation libraries. Even without these, they still compile with the MSVC compiler under windows, the clang compiler under mac, and recent versions of gcc under ubuntu. However,  they need to be added for older versions of gcc distributed in RHEL derivatives like centOS.
=> Added missing library includes that prevented proper linking

.gitignore
There were some binary files missing from the .gitignore files so I went ahead and added them.
Just out of curiosity, is there some reason that we don't just blot out the whole binary folder with `/bin/*`?
=> Added missing binary files to .gitignore

libraries/disp3D/engine/model/3dhelpers/geometrymultiplier.cpp, libraries/disp3D/engine/model/items/common/abstractmeshtreeitem.cpp, libraries/disp3D/engine/model/items/digitizer/digitizertreeitem.cpp, libraries/disp3D/engine/model/items/freesurfer/fssurfacetreeitem.cpp, libraries/disp3D/engine/model/items/network/networktreeitem.cpp, libraries/disp3D/engine/model/items/sensordata/gpuinterpolationitem.cpp, libraries/disp3D/engine/model/items/sensorspace/sensorpositiontreeitem.cpp, libraries/disp3D/engine/model/items/sensorspace/sensorsurfacetreeitem.cpp, libraries/disp3D/engine/model/items/sourceactivity/ecddatatreeitem.cpp, libraries/disp3D/engine/model/items/sourcespace/sourcespacetreeitem.cpp, libraries/disp3D/engine/model/materials/geometrymultipliermaterial.cpp, libraries/disp3D/engine/model/materials/geometrymultipliermaterial.h, libraries/disp3D/engine/model/materials/gpuinterpolationmaterial.cpp, libraries/disp3D/engine/model/materials/gpuinterpolationmaterial.h, libraries/disp3D/engine/model/materials/networkmaterial.cpp, libraries/disp3D/engine/model/materials/networkmaterial.h, libraries/disp3D/engine/model/materials/pervertexphongalphamaterial.cpp, libraries/disp3D/engine/model/materials/pervertexphongalphamaterial.h, libraries/disp3D/engine/model/materials/pervertextessphongalphamaterial.cpp, libraries/disp3D/engine/model/materials/pervertextessphongalphamaterial.h, libraries/disp3D/engine/model/materials/shownormalsmaterial.cpp, libraries/disp3D/engine/model/materials/shownormalsmaterial.h, libraries/disp3D/engine/view/customframegraph.cpp, libraries/disp3D/engine/view/customframegraph.h, libraries/disp3D/engine/view/view3D.cpp
I extended the frame graph to render transparent and opaque objects correctly.
All render states used for transparency are now defined in the frame graph and were deleted form the materials.
The PerVertexPhongAlphaMaterial also has an option to sort the objects using it before rendering.
=> [LIB-138] Fix transparency in Disp3D & [LIB-189] make frame graph work with OpenGL < 3.3

libraries/disp3D/engine/model/3dhelpers/geometrymultiplier.cpp, libraries/disp3D/engine/model/items/common/gpuinterpolationitem.cpp, libraries/disp3D/engine/model/items/common/gpuinterpolationitem.h
Made some small changes to the Gpu interpolation and geometry multiplier:
- Replaced QBuffer::updateData with setData. This was suggested here: https://bugreports.qt.io/browse/QTBUG-50720
- Fixed the bug "No shader program found" when running Disp3D in debug mode
- Moved the compute command and work group size definition to the right position.
=> [LIB-176] Gpu Interpolation Improvements

.travis.yml, tools/travis/linux_release/after_success.sh, tools/travis/linux_release/before_install.sh, tools/travis/linux_release/install.sh
Upload Linux pre-built binaries to Azure storage using azcopy. This also improves the download speed from our download website. We should consider uploading win and mac builts like this. 
The nature of the curl/ftp upload problem can be found [here](https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci).
=> Fix linux upload

tools/travis/documentation/after_success.sh, tools/travis/documentation/before_install.sh, tools/travis/documentation/install.sh, tools/travis/linux_release/before_install.sh
- Upload qch file to Azure instead of using git lfs. git lfs was a bit problematic because it can easily run out of quota. 
- Amend commits when updating docu. This way the git history does not grow with so many files being tracked.
=> [ENH] Docu upload

.gitignore
Removed some white spaces from .gitignore which prevented the bin and lib folder to be excluded under Linux.
=> Remove white spaces from .gitignore

applications/mne_scan/libs/scDisp/realtimeevokedsetwidget.cpp, applications/mne_scan/libs/scDisp/realtimemultisamplearraywidget.cpp, applications/mne_scan/libs/scDisp/realtimemultisamplearraywidget.h, libraries/disp/disp.pro, libraries/disp/viewers/fiffrawviewsettings.cpp, libraries/disp/viewers/fiffrawviewsettings.h, libraries/disp/viewers/formfiles/fiffrawviewsettings.ui, libraries/disp/viewers/helpers/rtfiffrawviewdelegate.cpp, libraries/disp/viewers/helpers/rtfiffrawviewdelegate.h, libraries/disp/viewers/helpers/rtfiffrawviewmodel.cpp, libraries/disp/viewers/helpers/rtfiffrawviewmodel.h, libraries/disp/viewers/rtfiffrawview.cpp, libraries/disp/viewers/rtfiffrawview.h
Renaming was performed in order to ease the port of the new offline browser, implemented in mne_analyze, to the Disp library.
=> Rename ChannelDataview to RtFiffRawView.

applications/applications.pro, libraries/libraries.pro, mne-cpp.pri, mne-cpp.pro
- Add wasm flag to MNECPP_CONFIG
- If set configures MNE-CPP to be compatible with qt wasm
- Currently Qt3D is not supported to build against wasm see [here](https://forum.qt.io/topic/109166/wasm-support-for-qt3d/4). This means we cannot build disp3d when the wasm flag is set.
@juangpc This should ease building MNE-CPP against qt wasm.
=> Add wasm flag

.github/workflows/devbuilds.yml
Currently we upload doxygen pages to mne-tools/mne-cpp:gh-pages. This slows down cloning and fetching the mne-cpp repo quite a bit, since the doxygen docu inlucdes >10k files. Therefore, changed upload to different repo.
This will free gh-pages for the new docu as proposed in #435.
=> Change upload target for doxygen docu

.github/workflows/coverity.yml
Move coverity build from ubuntu latest to 16.04 because of temporary install qt action bug jurplel/install-qt-action#19
=> Move coverity build to ubuntu 16.04

applications/mne_scan/plugins/rtcmusic/rtcmusic.pro
Fix typo in debug lib name for rtcmusic plugin
=> fix lib name for rtcmusic plugin

README.md
Currently the url leads to https://mne-cpp.github.io/team.html, which does not exist. Changed it to https://mne-cpp.github.io/contact.html
=> [FIX] Change Contact url to lead to correct page

examples/ex_hpiFit/main.cpp, libraries/utils/generics/applicationlogger.cpp, testframes/test_hpiFit/test_hpiFit.cpp
Fix #500 
- DWORD produced errors in Win7 and it is not used in Win10 either, so it is deleted. 
- test: minor changes
- example: use time vector instead of position file since this is the most likely usecase; Don't write error as gof in position file
=> [Fix] Custom Logger and small refactoring

resources/mne_rt_server_plugins/FiffSimulation.cfg, tools/wizards/mnecpp/example/main.cpp
Example wizard: 
- remove typo and add library
- remove return redundancy
- use QCoreApplication instead of QApplication to avoid error and:
> QCoreApplication - base class. Use it in command line applications.
QGuiApplication - base class + GUI capabilities. Use it in QML applications.
QApplication - base class + GUI + support for widgets. Use it in QtWidgets applications.
https://forum.qt.io/topic/94834/differences-between-qapplication-qguiappication-qcoreapplication-classes/3
FiffSimultor.cfg:
- use full path since it might be necessary on some operating systems (e.g. CentOs)
=> [Fix] Small fixes in example wizard and FiffSimulator.cfg

libraries/disp3D/viewers/formfiles/hpiview.ui, libraries/disp3D/viewers/hpiview.cpp, libraries/disp3D/viewers/hpiview.h, libraries/mne/c/mne_surface_or_volume.cpp, libraries/mne/c/mne_surface_or_volume.h, libraries/utils/sphere.cpp
This PR enables alignment and scaling of an average head surface to loaded digitizes. Part of this process were:
- fix problems in old MNE-C routines for align_fiducials and fit_sphere_to_points
- delete all unnecessary surfaces
Alignment and Scaling:
- load average head and digitizes
- align and scale (in head space)
- apply head_dev from cHPI fit for real time monitoring
Closes #474
=> [ENH] Scaling and aligning average head to fiducials and hpi in HPI-View 

.github/workflows/devbuilds.yml, applications/mne_scan/mne_scan/mne_scan.pro
This PR introduces the following changes:
- Only pull brainflow submodule in devbuilds workflow
- Change ordering when building brainflow plugin on MacOS workflow
- Copy brainflow libs into mne-cpp/lib in Linux workflow
- Remove .dmg flag in mne_scan.pro
- Include examples and other cmd line tools to mac os builds. Closes #482
=> [FIX,MAINT] Try to fix Linux and MacOS workflow

examples/ex_hpiFit/main.cpp, libraries/inverse/hpiFit/hpifit.cpp, libraries/inverse/hpiFit/hpifit.h, testframes/test_hpiFit/test_hpiFit.cpp
This PR contains:
- fuction to assign frequencies to coil position if unknown
- add this function to HPIFit in inverse lib
- implement the new function in ex_hpiFit and test_hpiFit
How does it work:
- fill vFreqs with the same frequency, different in each iteration
- call fitHpi nFrequency times 
- choose coil-Freqency assignment with maximal gof
=> [ENH] Add automatic frequency ordering to HPIFit

applications/mne_scan/libs/scDisp/realtime3dwidget.cpp, applications/mne_scan/plugins/hpi/FormFiles/hpisetup.ui, applications/mne_scan/plugins/hpi/FormFiles/hpisetupwidget.cpp, applications/mne_scan/plugins/hpi/hpi.cpp, applications/mne_scan/plugins/hpi/hpi.h, examples/ex_hpiFit/main.cpp, libraries/disp/viewers/formfiles/hpisettingsview.ui, libraries/disp/viewers/hpisettingsview.cpp, libraries/disp/viewers/hpisettingsview.h, libraries/inverse/hpiFit/hpifit.cpp, libraries/inverse/hpiFit/hpifit.h, libraries/inverse/hpiFit/hpifitdata.cpp, libraries/inverse/hpiFit/hpifitdata.h, libraries/rtprocessing/rthpis.cpp, libraries/rtprocessing/rthpis.h, testframes/test_hpiFit/test_hpiFit.cpp
This PR adds the frequency ordering to the hpi plugin in mne-scan and improves the performance of the hpi fitting. 
**frequency ordering:**
- add a push button to control panel and implement it into the hpi-plugin
**performance improvement:**
I was able to improve the performance of the hpi fit from **~250 ms** per fit to **~65 ms** per fit on my laptop. I got this improvement by:
- move calculation of everything that only has to be calculated once to the constructor (~225 ms)
- optimize parameters of minimization algorithm fminsearch (~112 ms)
- replace qlist in Sensor Struct with Eigen Matrices (~65 ms)
The result is shown in the following figure, just to give an impression. The values are calculated on one .fif file and all in all ~360 fits were performed. The figure shows the result …
=> [WIP][ENH,MAINT] Accelerate HPI fit and add freq ordering to plugin 

applications/mne_scan/libs/scDisp/realtimeevokedsetwidget.cpp, applications/mne_scan/libs/scDisp/realtimemultisamplearraywidget.cpp, applications/mne_scan/mne_scan/main.cpp, applications/mne_scan/plugins/babymeg/babymeg.cpp, applications/mne_scan/plugins/brainamp/brainamp.cpp, applications/mne_scan/plugins/eegosports/eegosports.cpp, applications/mne_scan/plugins/fiffsimulator/fiffsimulator.cpp, applications/mne_scan/plugins/ftbuffer/ftbuffer.cpp, applications/mne_scan/plugins/gusbamp/gusbamp.cpp, applications/mne_scan/plugins/lsladapter/lsladapter.cpp, applications/mne_scan/plugins/natus/natus.cpp, applications/mne_scan/plugins/noisereduction/noisereduction.cpp, applications/mne_scan/plugins/rtcmne/rtcmne.cpp, applications/mne_scan/plugins/rtcmne/rtcmne.h, applications/mne_scan/plugins/tmsi/tmsi.cpp, libraries/disp/viewers/filterdesignview.cpp, libraries/rtprocessing/rtfilter.cpp, libraries/rtprocessing/rtfilter.h
- Fix rt filtering problem where timings of channels, which were not filtered, were mismatched with the rest of the data
- Remove noise reduction tools in rt averaging control GUI
- Fix data handling in source loc plugin
- Clear buffers after stopping sensor plugins 
- Impose minimum size for the rt raw data display
- Define `RtFilter::filterChannel()` as static instead of global
=> [FIX, ENH] Fix rt filtering and improve rt averaging control

examples/ex_hpiFit/main.cpp, libraries/inverse/hpiFit/hpifit.cpp, libraries/inverse/hpiFit/hpifit.h
This PR adds an advanced model for the sinoides by adding line frequency and harmonics, linear componend and DC componend . This is implemented as extra mode, so you have to choose it when initializing the constructor. Per default, the fast and basic model is used.
=> [ENH] Add advanced model for hpi fit

applications/mne_scan/plugins/fiffsimulator/fiffsimulator.cpp, applications/mne_scan/plugins/fiffsimulator/fiffsimulatorproducer.cpp
Fix crashes relating to the FiffSimulator plugin in MNE Scan introduced by initializing some pointer too late.
=> [FIX] Fix FiffSimulator crashes

applications/mne_scan/plugins/fiffsimulator/fiffsimulator.cpp, applications/mne_scan/plugins/fiffsimulator/fiffsimulator.h, applications/mne_scan/plugins/fiffsimulator/fiffsimulatorproducer.cpp, applications/mne_scan/plugins/fiffsimulator/fiffsimulatorproducer.h, libraries/communication/rtClient/rtcmdclient.cpp
- Fix missing default port for rt data clients (port = 4218)
- Add some documentation and enforce coding conventions
- Improve operator precedence as pointed out by @juangpc
=> [FIX] Fix default ports in FiffSimulator plugin

.github/workflows/devbuilds.yml
The devbuilds workflow is currently failing due to linuxdeployqt not finding libbluetooth3, which was introduced during the last PR #562. This PR should fix it.
=> [MAINT] Add libbluetooth3 install to Linux workflow

.github/workflows/devbuilds.yml
The github action workflows for building a static version take over 60min. The GITHUB_TOKEN, which is created automatically by Github, is only valid for 60 minutes, see [here](https://github.community/t5/GitHub-Actions/error-Bad-credentials/td-p/33500). This PR adds a new acces token.
=> [MAINT] Add new github secret

.github/workflows/coverity.yml, .github/workflows/devbuilds.yml, .github/workflows/pullrequest.yml, applications/mne_anonymize/mne_anonymize.pro, applications/mne_rt_server/mne_rt_server/mne_rt_server.pro, applications/mne_scan/mne_scan/mne_scan.pro, applications/mne_scan/plugins/averaging/averaging.pro, applications/mne_scan/plugins/babymeg/babymeg.pro, applications/mne_scan/plugins/brainflowboard/brainflowboard.pro, applications/mne_scan/plugins/covariance/covariance.pro, applications/mne_scan/plugins/fiffsimulator/fiffsimulator.pro, applications/mne_scan/plugins/hpi/hpi.pro, applications/mne_scan/plugins/natus/natus.pro, applications/mne_scan/plugins/neuronalconnectivity/neuronalconnectivity.pro, applications/mne_scan/plugins/noisereduction/noisereduction.pro, applications/mne_scan/plugins/rtcmne/rtcmne.pro, applications/mne_scan/plugins/writetofile/writetofile.pro, doc/gh-pages/pages/development/qtwasmtutorial.md, doc/gh-pages/pages/development/staticbuild.md, doc/gh-pages/pages/started/started.md, mne-cpp.pri, testframes/test_mne_anonymize/test_mne_anonymize.pro
This PR adds the missing static builds for Windows. It includes the following changes:
- Some minor improvements to the "WebAssembly Build Guide" docu page , see [here](http://lorenze.github.io/mne-cpp/pages/development/qtwasmtutorial.html)
- Add windows guide to the static build guide docu page, see [here](http://lorenze.github.io/mne-cpp/pages/development/staticbuild.html)
- Add the Windows static builds to the Github action workflow, see [here](https://github.com/LorenzE/mne-cpp/blob/98aed624a92726ee9e4863793f05d4726fabf465/.github/workflows/devbuilds.yml#L129)
- Add missing static flags and defines to most of the MNE Scan plugins. This fixed building MNE Scan on Windows statically
- Fix static flag from `staticlib` to `static` in mne_scan.pro
- Prevent the call of `windeployqt` when …
=> [MAINT,DOCU] Fix static windows builds and add them to CI

applications/mne_rt_server/mne_rt_server.pro, applications/mne_rt_server/mne_rt_server/connectormanager.cpp, applications/mne_scan/mne_scan.pro
Use the [QStaticPlugin struct](https://doc.qt.io/qt-5/qstaticplugin.html) to fix meta data handling in mne_rt_Server plugins when building statically.
=> [MAINT] Fix meta data loading when building statically

applications/mne_anonymize/settingscontroller.cpp
I just want to show the help text whenever thee input parse did not work. 
Compiles and runs just fine. should've been implemented from the beginning.
=> [ENH] MNE_ANONYMIZE show help in case of invaild option parsing

.gitmodules
I've moved brainflow from my own account to new github org, maybe redirect works automatically but would be safer to update submodule url
=> Update brainflow submodule

.github/workflows/devbuilds.yml, .github/workflows/generateBinaries.yml, .github/workflows/pullrequest.yml
This PR adds support for pre-built static Qt versions generated with the new generateBinaries workflow. Please note that everytime we change our Qt version in the CI workflows we have to rerun the generateBinaries workflow again. This PR also add static build checks to the PR workflow. 
Closes #575
=> [MAINT] Add pre-built static Qt versions to CI workflows

.github/workflows/release.yml, applications/mne_analyze/extensions/annotationmanager/annotationmanager.cpp, applications/mne_analyze/extensions/annotationmanager/annotationmanager.h, applications/mne_analyze/extensions/dataloader/dataloader.cpp, applications/mne_analyze/libs/anShared/Management/analyzedata.h, applications/mne_analyze/libs/anShared/Management/extensionmanager.cpp, applications/mne_analyze/libs/anShared/Model/abstractmodel.h, applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.cpp, applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.h, applications/mne_scan/libs/scShared/Management/pluginmanager.cpp, libraries/fiff/fiff_io.cpp, libraries/fiff/fiff_io.h
- Fix crashing when a fif file without raw data was loaded
- Only load .dll plugin files on windows and improve command line output (MNE Scan and MNE Analzye)
- Fix memory leaks when closing MNE Analyze
- Change logo which shows up when loading WASM version of MNE Analyze
- Fix authors in FiffIO class
=> [ENH,FIX] MNE Analyze improvements

applications/mne_analyze/mne_analyze/mne_analyze.pro
Fix deployment of MNE Analyze plugins on macOS. We copied the source code of each plugin instead of their binaries during deployment. This bug should have no affect on the static builds. Closes #593
=> [FIX] Fix deployment of MNE Analyze plugins on macOS

examples/ex_hpiFit/main.cpp, libraries/communication/rtClient/rtdataclient.cpp, libraries/fiff/fiff_info.cpp, libraries/fiff/fiff_info.h, libraries/fiff/fiff_stream.cpp
This PR fixes a wrong datatype (float -> fiff_int_t) used in fiff_info and fiff_stream. This was most likely the reason for file reading problems.
=> [MAINT]: Fix datatype in fiff_info and fiff_stream

applications/mne_scan/plugins/rtcmne/rtcmne.cpp
This PR initializes the control widget before checking if the initialized event id equals the incoming event. Hence you can choose your trigger and are not dependent on having the in rtcmne initialized event type in your data. 
This PR closes #620 .
=> [Fix] Solve init event id/trigger problem in Source Loc. plugin

applications/mne_analyze/libs/anShared/Management/statusbar.cpp, applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.cpp, applications/mne_analyze/mne_analyze/mainwindow.cpp, applications/mne_analyze/mne_analyze/mainwindow.h, applications/mne_analyze/mne_analyze/mne_analyze.qrc, applications/mne_analyze/plugins/annotationmanager/annotationmanager.cpp, applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.cpp, applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.h, applications/mne_analyze/plugins/datamanager/datamanager.cpp, applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp, applications/mne_analyze/plugins/rawdataviewer/fiffrawviewdelegate.cpp, applications/mne_analyze/plugins/rawdataviewer/rawdataviewer.cpp, applications/mne_scan/mne_scan/mainwindow.cpp, applications/mne_scan/mne_scan/mne_scan.qrc, libraries/disp/viewers/multiview.cpp, libraries/disp/viewers/multiview.h, libraries/disp/viewers/multiviewwindow.cpp
- MNE analyze now remembers which plugins were open/closed and location on screen from last session.
- deleting annotations now consistent whether selecting bottom to top or top to bottom 
- linux icons now in resource files, adjusted path in both Scan and Analyze
- clean up syntax/variable typing to reduce compilation warnings
Closes #606
=> [ENH, MAINT] MNE Analyze state saving, bugfixes, cleanup, linux icon. MNE Scan linux icon

applications/mne_analyze/libs/anShared/Management/analyzedata.cpp, applications/mne_analyze/libs/anShared/Management/analyzedata.h, applications/mne_analyze/libs/anShared/Management/analyzedatamodel.cpp, applications/mne_analyze/libs/anShared/Management/analyzedatamodel.h, applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.cpp, applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.h, applications/mne_analyze/libs/anShared/anShared.pro, applications/mne_analyze/plugins/dataloader/dataloader.cpp
- Update Brainflow module. This will fix building mne-cpp with brainflow support under MSVC 2019
- Introduce new analyze data model, which organizes the data subject wise.
- Remove the isolated loadFiffRawModel function in AnalyzeData. QByteArray support is now included in the loadModel function.
=> [MAINT,ENH] MNE Analyze data model improvements, update Brainflow module 

examples/ex_spectral/ex_spectral.pro
Hi,
In the example ex_spectral, a small typo in the name of the fiff library in debug mode would not allow the project to compile directly in debug mode.
=> solve fiff lib typo in example spectral and debug mode

applications/mne_scan/plugins/hpi/hpi.cpp, libraries/disp/viewers/hpisettingsview.cpp, libraries/inverse/hpiFit/hpifit.cpp
This PR introduces following fixes and therefore closes #639:
**HPI plugin**
- clear device - head transformation for single fit to always use seed points for better handling of single fits that are performed after a while
**HPI Library**
- use seedpoints if last fit was bad
- clear dev head trans in findOrder. This is necessary if accedantly a hpi fit is performed before ordering
**HPI Widget**
- store state of continious hpi checkbox.
=> [Fix] reset Hpi fitting properly

applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.cpp, libraries/rtprocessing/filter.cpp, libraries/rtprocessing/filter.h
Revert always changing the filter order to 4096 when using the `filterFile()` function. This is too intransparent for the user/developer. Let the user decide/make sure that the filter kernel has a sufficient filter length. In MNE Analyze we now redesign the filter to 4096 before saving to file.
=> [ENH] Revert setting default filter length 

applications/mne_anonymize/apphandler.h, applications/mne_anonymize/mainwindow.h, applications/mne_anonymize/settingscontrollercl.cpp, doc/gh-pages/pages/install/binaries.md, doc/gh-pages/pages/learn/dipolefit.md, doc/gh-pages/pages/learn/fwdsolution.md, doc/gh-pages/pages/learn/mneanonymize.md
Hi, there were 24 uses of "command-line" **with** hyphen in the code base and about 150 **without**. Most of the uses came from the damn anonymize app... 🤫.
We now use no hyphen in the term. Little bit of coherence can't hurt. 
Besides I've come through [this](https://dzone.com/articles/blogging-programmers#:~:text=%22Open%2DSource%22%20and%20%22,noun%20or%20a%20compound%20adjective) interesting post, which besides it being quite old, I think it is still valuable.
Also added the link to anonymize wasm and change the title in the docs.
=> [MAINT, DOC] Use "command line" without hyphen and add link to mne_anonymize wasm 

applications/mne_analyze/libs/anShared/Model/annotationmodel.cpp, applications/mne_analyze/libs/anShared/Model/annotationmodel.h, applications/mne_analyze/plugins/annotationmanager/annotationsettingsview.cpp, applications/mne_analyze/plugins/averaging/averaging.cpp
Fixed issue where function was trying to get the name from an invalid index from iterating over map while not looking up the list of keys before reading from the map. Also changed return of function from QString& to QString for best practices.
=> [FIX] MNE Analyze: fixed indexing when updating event group list.

applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.cpp, applications/mne_analyze/libs/anShared/Model/fiffrawviewmodel.h, applications/mne_analyze/plugins/rawdataviewer/fiffrawviewdelegate.cpp, examples/ex_disp_3D/main.cpp, libraries/disp/viewers/averagelayoutview.cpp, libraries/disp/viewers/butterflyview.cpp, libraries/disp3D/engine/model/data3Dtreemodel.h
- Fix data plotting when scrolling to the left (raw and filtering). Fixed a problem where the current fiff curser of the beginning data block was substracted by the filter delay even if filtering was disabled. Fixes #659
- Remove `filterAllData` function and replace usage by `reloadAllData`, which leads to an performance improvement
- Rename `updateDisplayData` to `reloadAllData`
- Comment out some qInfo outputs
- Rename `getWindowSizeBlocks` to `getTotalBlockCount`
- Disable downsampling when plotting since it introduced aliasing effects
=> [FIX] Fix data plotting when scrolling to the left in MNE Analyze

applications/mne_analyze/libs/anShared/Interfaces/IPlugin.h, applications/mne_analyze/libs/anShared/Management/pluginmanager.cpp, applications/mne_analyze/mne_analyze/analyzecore.cpp, applications/mne_analyze/mne_analyze/analyzecore.h, applications/mne_analyze/mne_analyze/main.cpp, applications/mne_analyze/plugins/dataloader/dataloader.cpp, applications/mne_analyze/plugins/dataloader/dataloader.h, applications/mne_anonymize/main.cpp
- Add new feature to specify the file to be opened with MNE Analyze via the cmd line. Usage `mne_analyze --file sample_audvis_raw.fif` or `mne_analyze -f sample_audvis_raw.fif`. Closes #601 
- Added general functionality to initialize MNE Analyze plugins based on cmd line inputs.
- Bump up version to 0.1.5 in MNE Anonymize
=> [ENH] Add cmd line argument support to MNE Analyze

.github/workflows/pullrequest.yml, .github/workflows/release.yml
- Add apt-update to fix mesa-dev package download in linux static ci build
=> [FIX] Fix mesa-dev package download in linux static ci builds

.github/workflows/buildqtbinaries.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml, .github/workflows/wasmtest.yml, applications/mne_analyze/mne_analyze/mne_analyze.pro, applications/mne_analyze/plugins/averaging/averaging.pro, applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp, applications/mne_analyze/plugins/rawdataviewer/rawdataviewer.pro, applications/mne_anonymize/mne_anonymize.pro, applications/mne_scan/libs/scDisp/scDisp.pro, applications/mne_scan/mne_scan/mne_scan.pro, doc/gh-pages/pages/install/buildguide_dynamic.md, doc/gh-pages/pages/install/buildguide_static.md, libraries/disp/disp.pro, libraries/disp/viewers/averagelayoutview.cpp, libraries/disp/viewers/butterflyview.cpp, libraries/disp/viewers/butterflyview.h, libraries/disp/viewers/rtfiffrawview.cpp, mne-cpp.pri, mne-cpp.pro
- Bump CI to Qt 5.15.1
- Rename `noOpenGL` to `noQOpenGLWidget` flag
- For Qt version >= 5.15.0 set noQOpenGLWidget automatically. There are some problems with that version and the QOpenGLWidget.
=> [MAINT] Bump up CI Qt version to 5.15.1 

libraries/disp3D/engine/view/view3D.cpp, libraries/disp3D/engine/view/view3D.h
This PR implements triangle picking of custom mashes, such as the Bem surface.
Therefore following member functions and variables were implemented into DISP3DLIB::View3D.
Public:
- `void activatePicker(const bool bActivatePicker);` activates/deactivates the Picker. Picking can need quite some performance if a lot of Triangles/Vertices/etc. are involved. Therefore, it is helpful only to activate it if necessary.
Protected:
- `void initObjectPicking();` - initialize the QObjectPicker
- `void handlePickerPress(Qt3DRender::QPickEvent *qPickEvent);` - called whenever a picking event occure. Emits an signal if the left mouse button is the origin.
Signal:
- `void pickEventOccured(Qt3DRender::QPickEvent *qPickEvent);` Emitten, when picking event occured
=> [ENH] MNE-Lib: Implement triangle picking 

.github/workflows/buildqtbinaries.yml, .github/workflows/release.yml, .github/workflows/wasmtest.yml, doc/gh-pages/pages/development/wasm_buildguide.md, mne-cpp.pri, mne-cpp.pro
- Fix the Wasm CI workflow. The utils library was not able to be compiled with Emscripten v1.39.8 and therefore was decreased to v1.39.7
- Fix compiler flag usage by moving them back to the mne-cpp.pri file which is included by all other .pro files.
=> [MAINT,FIX] Fix Wasm CI workflow

.github/workflows/pullrequest.yml, .github/workflows/release.yml
- Fix mnecpp library copying on macos. macdeployqt -libpath seems to not have an effect.
- Fix mkdir in windows workflow.
=> [MAINT] Fix library copying on macos. Fix mkdir in windows workflow.

.github/workflows/buildqtbinaries.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml, doc/gh-pages/pages/development/ci_deployment.md, doc/gh-pages/pages/install/binaries.md, mne-cpp.pri, tools/deployment/deploy_linux, tools/deployment/deploy_linux_static, tools/deployment/deploy_macos, tools/deployment/deploy_macos_static, tools/deployment/deploy_win.bat, tools/deployment/deploy_win_static.bat
- Update ubuntu runners
- Update dropbox links
- Update mne-cpp-test-data submodule to newest commit
- Create new static deployment scripts
- Use linuxdeployqt for linux static builds as well
- Update deployment documentation
- Link download links on our website to always point to dynamic versions
Note:
- Static deployment for Linux builds is still problematic, since the xcb platform plugin is not working. Static deployment for Win and MacOS work fine.
=> [MAINT] Update static/dynamic deployment process

.github/workflows/release.yml
- Remove hub install action in release.yml since HUB CLI is already a part of all runners.
=> [MAINT] Remove hub install action

libraries/disp/viewers/control3dview.cpp, libraries/disp/viewers/control3dview.h, libraries/disp3D/engine/model/items/digitizer/digitizersettreeitem.cpp
* Fix fiducial coloring problem in Disp3D.
* Change fiducial colors to match the ones of mne-python.
* Add remove option to context menu (right click) in the Control3DView. Subsequently, the 3D data is removed from the 3D data model and view.
=> [FIX,ENH] Fix digitizer visualization and allow removing 3D items

.github/workflows/buildqtbinaries.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml, .github/workflows/testci.yml, .github/workflows/wasmtest.yml, mne-cpp.pri
- Update CI to use Qt 5.15.2, which solves [a problem](https://bugreports.qt.io/browse/QTBUG-88590) with Qt3D on MacOS
- Remove setting the noOpenGLWidget flag when Qt version is >5.15.0. This basically makes MNE Scan and the signal plotting useless on MacOS.
=> [MAINT] Update to Qt 5.15.2

doc/gh-pages/pages/install/buildguide_dynamic.md, doc/gh-pages/started.md
It looks like a pages directory was added which broke the links that were in the directory above pages (i.e. doc).
=> [DOC, BUG, MRG] Fix started.html links

doc/gh-pages/pages/install/changelog.md, doc/gh-pages/started.md
This PR fixes some dead links which were introduced in #730. I did not see these in your PR @alexrockhill. Sry about that. I should have checked your PR by deploying your changes against Github Actions. A guide on how to do so yourself can be found [here](https://mne-cpp.github.io/pages/development/contr_docuimprovements.html). The setup only needs to be done once.
This PR also fixes some layout issues in the changelog.
=> [DOC] Fix links in docu

libraries/disp3D/engine/model/3dhelpers/renderable3Dentity.cpp, libraries/disp3D/engine/view/view3D.cpp, libraries/disp3D/engine/view/view3D.h
- Docu fixes in Renderable3DEntity
- Fix applying the same rotation animation on the parent and children of a Renderable3DEntity. This led to <the number of children> faster animations. We now only apply the animation on the parent. This solves one problem reported in #731.
- Make use of parallel animation starting via `QParallelAnimationGroup`.
=> [FIX] Fix speed of model rotation

tools/testing/test_win.ps1
This makes it easier for the developer to be able to test the tests locally, from a terminal.
=> [ENH] Make test_win powershell script to be callable from anywhere

applications/mne_analyze/libs/anShared/Model/averagingdatamodel.cpp, applications/mne_analyze/plugins/annotationmanager/annotationmanager.cpp, applications/mne_analyze/plugins/annotationmanager/annotationmanager.h, applications/mne_analyze/plugins/averaging/averaging.cpp
- fix leak in communicator pointer not being deleted (used shared pointer)
- fix clearing of averaging views by returning correct pointer when getting evoked set and evoked model
=> [FIX] MNE Analyze leak fix, library get function fix

applications/mne_analyze/plugins/view3d/view3d.cpp, applications/mne_scan/libs/scDisp/realtime3dwidget.cpp, libraries/disp3D/engine/view/orbitalcameracontroller.cpp, libraries/disp3D/engine/view/orbitalcameracontroller.h, libraries/disp3D/engine/view/view3D.cpp, libraries/disp3D/engine/view/view3D.h, libraries/disp3D/viewers/abstractview.cpp
Sorry this took so long to have a decent enough start to commit @LorenzE! I think I have the lay of the land and can work on a solution. I'm trying to implement it like here https://doc.qt.io/qt-5/qt3d-simple-cpp-example.html (I tried first with `QCamera::panAboutViewCenter` but I guess you can't animate functions only properties?). It's still crashing but I was going to work on it for another hour or so and then maybe ask for help if it's still breaking.
=> [BUG] Orbit camera instead of rotating objects in 3D view

applications/mne_anonymize/fiffanonymizer.cpp, applications/mne_anonymize/fiffanonymizer.h, applications/mne_anonymize/mainwindow.cpp, applications/mne_anonymize/mainwindow.h, applications/mne_anonymize/mainwindow.ui, applications/mne_anonymize/settingscontrollergui.cpp
In fiff files, birthday date is coded in julian calendar (with an integer number).  It is just a date, not a date and time. Thus, I change here the use of QDateTime for the use of QDate for a more correct use. 
I also got to change the use of const references more to gain a bit of simplicity/efficiency. 
Let's see what I break.
=> [FIX]  MNEAnonymize Use QDate instead of QDateTime when reffering to birthday date.

applications/mne_scan/plugins/writetofile/writetofile.cpp, applications/mne_scan/plugins/writetofile/writetofile.h
- Fix writing to file with wrong values by not accounting for calibration (calling correct write_raw_buffer)
=> [FIX] MNE Scan - writing to file calibration values

applications/mne_anonymize/mne_anonymize.pro
We were experiencing different behavior between platforms. Now it works fine.
=> [FIX] add console to CONFIG qt pro file

applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp, applications/mne_analyze/plugins/rawdataviewer/fiffrawview.h
Hi, 
There is a problem with the way info is now displayed in the plugin rawdataviewer in mne_analyze. Instead of printing the information of the file and the filter applied in the title bar, we can do it at the bottom in a label bar. 
There is a little bit less space because there are other labels related to the time already printed there, but I think it is fine (at least for now).
=> [FIX] Show file and filter info beneath the data viewer

applications/mne_analyze/plugins/averaging/averaging.cpp, doc/gh-pages/pages/development/analyze_plugin.md
Hi, 
Some weeks ago I proposed this changed in another unrelated pr. Here is now a specific one for discussing this change. 
Going through mne_analyze plugin docs, I saw the code snippet for [the clone method](https://mne-cpp.github.io/pages/development/analyze_plugin.html). I think that this is OK, however it is improvable, due to the fact that: 
- Since it is a part of the code that is actually described in the documentation we should have special care. 
- The code is not wrong, but I don't think it is correct either. I haven't seen the asm but I'm quite certain that the compiler will get that code referred to the clone method and disregard it's implementation. 
- The change I propose makes explicit what the reader should know and understand as part of the c++ standard because it is …
=> [ENH] Use explicit copy elision in plugin::clone()

libraries/disp/viewers/helpers/scalecontrol.cpp
Adding <math.h> dependency to the new scalecontrol class implementation.
=> [FIX] - Solve compilation issues on linux platform

libraries/disp/viewers/scalingview.cpp
- In ScalingView destructor, remove map entry when deleting pointers to avoid infinite loop.
=> [FIX] Fix MNE Scan crashing on stop

applications/mne_analyze/libs/anShared/Management/communicator.cpp, applications/mne_analyze/libs/anShared/Management/communicator.h, applications/mne_analyze/libs/anShared/Management/eventmanager.cpp, applications/mne_analyze/libs/anShared/Management/eventmanager.h, applications/mne_analyze/mne_analyze/analyzecore.cpp
Hi, 
I wanted the functionality in the singleton EventManager to be accessible through static fcns. Right now it is set to the typical getInstance() method which then allows to retrieve public access to the class. Through this change (sugar) the api is directly accessible and it looks more natural to consume the class's API. 
+ bonus: In Communicator, there is a range for that was detaching from the Qt structure unnecessarily. Apparently, by making it const, c++ will iterate through references. Warnings-- (✊🏻)
=> [ENH] EventManager sintactic sugar

.github/workflows/coverity.yml
H, 
coverity.yml now makes Coverity depend on **master** branch instead of main. This pr address this. 
It also starts using a googlegroups email distribution list instead of using individual emails of developers.
=> [UPDATE] Make Coverity depend on Main branch and use googlegroups email address

applications/mne_analyze/plugins/rawdataviewer/fiffrawview.cpp, applications/mne_analyze/plugins/rawdataviewer/fiffrawview.h
Instead of allocating a new menu and action each time the right-click mouse button is pressed, we store and reuse.
=> [FIX] MNE_Analyze store right-click context menu in fiffrawview plugin as member variables.

applications/mne_scan/mne_scan/main.cpp, applications/mne_scan/mne_scan/mainsplashscreen.cpp, applications/mne_scan/mne_scan/mainsplashscreen.h, applications/mne_scan/mne_scan/mainsplashscreenhider.cpp, applications/mne_scan/mne_scan/mainsplashscreenhider.h, applications/mne_scan/mne_scan/mainwindow.cpp, applications/mne_scan/mne_scan/mainwindow.h, applications/mne_scan/mne_scan/mne_scan.pro
I make MNE Scan's splash screen hide 1 second after the main application's gui has finished its setup. During that second the splash screen can be hidden just by clicking on it, and since the splashscreen's management is offloaded to a new thread, even with the splash screen on top, the main GUI is still responsive. 
I think it gives a much sense of well tuned application. Since it is pretty much the first interaction with the user, i think it has some importance. 
More info... Some prs back, MNE Scan splash screen used to not be taken off by the application after it started. It would simply remain underneath the main gui window. I fixed that by making mne_scan's splash screen to hide the moment the initialization of the main screen had finished. Right before the main application loop …
=> [ENH] MNE_Scan splashscreen

examples/ex_fiff_sniffer/ex_fiff_sniffer.pro, examples/ex_fiff_sniffer/main.cpp, examples/examples.pro
It just prints a bunch of fiff metadata to console for the fiff file you point it at with --file . It is currently in examples, not sure what the best place for it would be (or if its even worth merging at all)
=> [ENH] Quick tool for spitting out fiff metadata

applications/mne_scan/plugins/ftbuffer/FormFiles/ftbuffersetupwidget.cpp, applications/mne_scan/plugins/ftbuffer/ftbuffer.cpp, applications/mne_scan/plugins/ftbuffer/ftbuffer.h, applications/mne_scan/plugins/ftbuffer/ftbuffproducer.cpp
- Attempt to connect to FieldTrip buffer on pressing start in MNE Scan.
This is part of the functionality that was present in the 'ssadhd' branch, but just the ftbuffer stuff decoupled from the hpi debugging.
=> [MAINT] Connect to ftbuffer on start

applications/mne_scan/plugins/ftbuffer/ftbuffer.cpp, applications/mne_scan/plugins/ftbuffer/ftbuffproducer.cpp, applications/mne_scan/plugins/ftbuffer/ftconnector.cpp, applications/mne_scan/plugins/ftbuffer/ftconnector.h
- Change logic to no longer expect (or need) neuromag extended header. Instead, default to minimal FiffInfo with made with data from simple ftbuffer header.
=> [ENH] Create default FiffInfo for FtBuffer with minimal metadata

applications/mne_anonymize/main.cpp, applications/mne_anonymize/mne_anonymize.pro, applications/mne_anonymize/settingscontrollercl.cpp, applications/mne_anonymize/settingscontrollercl.h
Couple of things in the app needed to get fixed. 
- Use of console only in debug mode. 
- delete a qdebug printing the date that got leaked into production version. 
- rewrite QMAKE_TARGET_DESCRIPTION variable so that windows task manager correctly prints the application name.
- fix a warning regarding a const qualifier in a signal.
- dont emit in constructors
=> [FIX] MNE Anonymize 

applications/mne_analyze/mne_analyze/mne_analyze.pro
QMAKE_TARGET_DESCRIPTION  is what Qt uses to populate whatever field window's task manager uses to name the applications listed there. It makes sense to populate it with the name of the applications. 
Regarding the console. It is not needed when working with analyze in release mode.
=> [FIX] MNE Analyze 

applications/mne_scan/libs/scShared/Management/pluginscenemanager.cpp, applications/mne_scan/plugins/ftbuffer/ftbuffer.cpp
- Remove internal requestInterruption/wait in ftbuffer stop function
- Add requestInterruption to all plugins before calling stop.
=> [WIP] MAINT, FIX: Change FtBuffer stop to fix crash and add thread interupt request before stopping plugins

applications/mne_anonymize/mainwindow.h
Qt signals should not carry a const qualifier.
=> [FIX] ANONYMIZER Delete unnecessary const qualifier for signals

applications/mne_scan/mne_scan/mainwindow.cpp, applications/mne_scan/plugins/hpi/hpi.cpp, applications/mne_scan/plugins/hpi/hpi.h, libraries/disp/viewers/formfiles/hpisettingsview.ui, libraries/disp/viewers/hpisettingsview.cpp, libraries/disp/viewers/hpisettingsview.h
Preamble:
This is not a permanent fix by any means, this is a quick fix to have the continuous hpi in its current state more easily debugable during runtime (with different setups). This is a control for making iNumberOfFitsPerSecond variable during runtime, which was found to be a temporary solution to getting the continuous hpi fitting working on different incoming frequencies and data chunk sizes. iNumberOfFitsPerSecond does not set the number of fits per second, it is used to set the sample window used to perform the continuous fit, but the fit still seems to occur at whatever rate the data comes in. Treat this as a tuning variable, find a setting that works and leave it there. With that being said:
- Add controls for setting fits per seocnd in HpiSettingsView
- Make …
=> [MAINT] Add 'fits per second' control to hpi.

applications/mne_scan/mne_scan/mainwindow.cpp, applications/mne_scan/plugins/ftbuffer/ftbuffer.cpp, applications/mne_scan/plugins/ftbuffer/ftbuffer.h, applications/mne_scan/plugins/ftbuffer/ftheaderparser.cpp, applications/mne_scan/plugins/ftbuffer/ftheaderparser.h, applications/mne_scan/plugins/hpi/hpi.cpp, examples/ex_fiff_sniffer/main.cpp
- Add read guards before operating on data that was opened from streams/files
- Calls by const reference
- Init member variables in constructor
Part of Juan's new 10 issues a week initiative.
=> MAINT: Fix some MNE Scan Coverity issues

applications/mne_analyze/libs/anShared/anShared.pro, applications/mne_scan/libs/scDisp/scDisp.pro, applications/mne_scan/libs/scMeas/scMeas.pro, applications/mne_scan/libs/scShared/scShared.pro, libraries/communication/communication.pro, libraries/connectivity/connectivity.pro, libraries/disp/disp.pro, libraries/disp3D/disp3D.pro, libraries/events/events.pro, libraries/fiff/fiff.pro, libraries/fs/fs.pro, libraries/fwd/fwd.pro, libraries/inverse/inverse.pro, libraries/mne/mne.pro, libraries/rtprocessing/rtprocessing.pro, libraries/utils/utils.pro
The usage of ```INSTALLS``` keyword in some of the projects ```.pro``` files makes the project to show twice all the header files. 
That is the case in the library layer, for instance. 
Is there a reason why we're using ```INSTALLS``` keyword?
=> [ENH] MNECPP - Comment installs keyword in pro files

applications/mne_scan/plugins/hpi/hpi.cpp
- load preset relative to directory of the executable rather than current working dir.
=> FIX: MNE Scan: use correct directory for hpi presets

applications/mne_scan/plugins/ftbuffer/ftconnector.cpp, applications/mne_scan/plugins/ftbuffer/ftconnector.h, libraries/rtprocessing/helpers/cosinefilter.cpp
- Prevent out of bounds access to Eigen structure that was sometimes causing a crash.
- Add min sample window to read from ftbuffer (quick fix for how filter plugin does max filter size).
=> MAINT: Fix filter plugin crash in MNE Scan, add min buffer read size.

libraries/mne/c/mne_msh_display_surface_set.cpp, libraries/mne/c/mne_msh_display_surface_set.h
In ```add_bem_surface``` there seems to be a leak of ```newSurf``` 
In ```add_replace_display_surface``` I'm not sure about ```surf``` variable. @LorenzE do you remember about this function?
=> [Fix] Memory leak in MNE library in bem related functions

libraries/fwd/fwd_comp_data.cpp
Double Frees. Free is already done in destructor ~FwdCompData
=> FIX: Coverity 16829-16832

examples/ex_hpiFit/main.cpp, examples/ex_read_fwd/main.cpp, examples/ex_spectral/main.cpp, libraries/utils/file.cpp, libraries/utils/generics/observerpattern.cpp, libraries/utils/generics/observerpattern.h, libraries/utils/ioutils.cpp, libraries/utils/ioutils.h, libraries/utils/kmeans.cpp, libraries/utils/kmeans.h, libraries/utils/layoutloader.cpp, libraries/utils/layoutloader.h, libraries/utils/layoutmaker.cpp, libraries/utils/layoutmaker.h, libraries/utils/mnemath.cpp, libraries/utils/mnemath.h, libraries/utils/selectionio.cpp, libraries/utils/selectionio.h, libraries/utils/spectral.cpp, libraries/utils/spectral.h, libraries/utils/warp.cpp, libraries/utils/warp.h, mne-cpp.pri, testframes/test_utils_circularbuffer/test_utils_circularbuffer.cpp, testframes/test_utils_circularbuffer/test_utils_circularbuffer.pro, testframes/testframes.pro
This goes over a majority of the utils library and adds a std lib api (and a std lib backend) to most classes and static functions.
- Overloaded functions with Qt-type parameters and return values with std lib versions.
- Changes internal logic where applicable to use std lib containers/classes
- When faced with functions with no input parameters and a qt return type, overloaded added and commented out.
Also:
- ~~min c++ version set to c++ 17 for use of filesystem library. Is this ok? this is a 5 year old standard at this point.~~
(reverted, was causing issues with ubuntu 18 and osx 10.15 and lower std lib version. No longer using filesystem lib. )
- Because adding more code results in a lower code coverage percentage even though the functions I overloaded were not being tested anyway (I …
=> [MAINT] Utils library Qt-less refactor (Part 1 of many)

applications/mne_scan/plugins/hpi/hpi.cpp, applications/mne_scan/plugins/hpi/hpi.h, libraries/disp/viewers/formfiles/hpisettingsview.ui, libraries/disp/viewers/hpisettingsview.cpp, libraries/disp/viewers/hpisettingsview.h
For a better understanding of whether fitting goes well and if the issue might be a particular coil, I added the Goodness of Fit (GoF ) next to the error in the `Quick Control` widget. 
In general, the error gives information about the transformation and the gof about the fit itself. So both should be presented next to each other
=> [ENH] MNE-Scan: show gof as well

.gitignore
Add entry to .gitignore so that QtCreator created build folders are ignored by git.
=> [MAINT] Add rule for ignoring qt-creator generated build folders

src/CMakeLists.txt
Defaults builds without a set build type to `"Release"`
=> Add Default build type in cmake

.github/workflows/buildqtbinaries.yml, .github/workflows/coverity.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml, .github/workflows/testci.yml
Ubunutu 18.04 is currently [deprecated and will soon be axed completely](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)
This PR changes actions to use `ubuntu-20.04` wherever a "minimum" version is appropriate, or `ubuntu-latest` elsewhere.
=> [MAINT] Update Github Actions Runners

tools/building/build_project.bat
Fix build flag passed with --D. Should be -D.
Have build script return exit with error if build fails.
Currently our script returns success (0), regardless of the success of the build. This leads to the unfortunate circumstance of ant GH Action step running this script to pass, regardless of whether the build itself was successful. Typically this did not make itself apparent, since there are subsequent steps that would fail in the absence of a build. PR #935 had failing static builds on mac and linux, but since there are no subsequent steps, the build passed. PR #936 addresses the static flag issue.
=> [FIX] build script return val

tools/deploy.bat
Currently our deploy script sets `PackOption` to `pack` instead of `true` in the Linux section of the script. When this is later checked in the script, it causes the packing code not to run, since we check for `"pack" == "true"`. This has resulted our Linux binaries not being generated whenever a release is triggered.
This PR makes a change to the linux section of the script, where command line arguments are parsed, fixing the setting of the pack variable to `true` in case the appropriate flag is passed. This makes the functionality mirror that of the macOS section, which is behaving correctly.
=> [FIX] Fix packing linux builds

tools/deploy.bat
In the deploy script, set pack dynamic output path to match static pack output path. This is currently different, causing release action not finding the resulting dynamic zipped pack.
=> [FIX] Match dynamic pack output path

.github/workflows/coverity.yml, tools/coverity_scan.sh
- Move shell script portion of CI to its own script.
- Make further changes to script logic to accommodate cmake and running locally.
=> [MAINT] Coverity Static Analysis

src/applications/mne_analyze/libs/anShared/Model/eventmodel.cpp, src/applications/mne_analyze/plugins/events/eventview.cpp, src/applications/mne_analyze/plugins/rawdataviewer/fiffrawviewdelegate.cpp, src/libraries/disp/viewers/helpers/rtfiffrawviewmodel.cpp, src/libraries/disp/viewers/scalingview.cpp, src/libraries/events/eventmanager.cpp, src/libraries/events/eventsharedmemmanager.cpp, src/libraries/fiff/fiff_ch_info.cpp, src/libraries/utils/selectionio.cpp, src/testframes/test_coregistration/test_coregistration.cpp
- iterate over references or const references when possible in range based or loops.
- remove memory leak in test
- remove potential UB uses of std::move.
- explicitly call default constructor of previously uninitialized members in default FiffChInfo constructor.
=> [MAINT] Fix some issues found by coverity scan

src/CMakeLists.txt, src/libraries/events/eventmanager.cpp, src/libraries/events/eventmanager.h
- Add CMake flag to build without ipc / shared memory features. (sets a macro)
- Quarantine shared memory usage in events lib.
To do:
=> WIP [MAINT] enable/disable ipc/shmem when building

tools/build_project.bat
Add correct echo flag `-e` on linux systems to escape special characters properly. (Tested on CentOS)
=> Fix colors on Linux

src/applications/mne_scan/plugins/rtfwd/rtfwd.cpp, src/applications/mne_scan/plugins/rtfwd/rtfwd.h, src/libraries/disp/viewers/formfiles/fwdsettingsview.ui, src/libraries/disp/viewers/fwdsettingsview.cpp, src/libraries/disp/viewers/fwdsettingsview.h, src/libraries/fwd/computeFwd/compute_fwd.cpp, src/libraries/fwd/computeFwd/compute_fwd_settings.h
Added functionality to allow for a flexible choice of the cluster size of the clustered forward solution. Before the cluster size was hard-coded.
Furthermore fixed a small bug which would lead to crashes due to a segfault:
Deleting the QSharedDataPointer in compute_fwd.cpp causes a segfault when later dereferencing *m_eeg_forward_grad.data()/*m_meg_forward_grad.data() in the call of compute_forward_eeg/compute_forward_meg.
There might be a way to fix this while still deleting the (basically empty) object behind the shared pointer. However, as far as I can see we do not have a guarantee that the value of m_pSettings->compute_grad does not change, so if it would switch to true later on and for some reason calculatedFwd() gets called we would have a problem with the current code anyway.
=> [ENH] Flexible choice of cluster size
